work_dir: ./data/data/ntu_result/xview/aagcn_v33_joint/delme
model_saved_name: ./data/data/ntu_result/xview/aagcn_v33_joint/delme/ntu_cv_aagcn_joint

phase: train
save_score: True

seed: 1
log_interval: 100 # iter
save_interval: 2 # iter
eval_interval: 5 # iter
print_log: true

# feeder
feeder: feeders.feeder.Feeder
num_worker: 4
train_feeder_args:
  data_path: ./data/data/ntu_nopad/xview/train_data_joint.npy
  label_path: ./data/data/ntu_nopad/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
#  random_zaxis_flip: True
#  random_xaxis_shift: True
#  random_yaxis_shift: True

test_feeder_args:
  data_path: ./data/data/ntu_nopad/xview/val_data_joint.npy
  label_path: ./data/data/ntu_nopad/xview/val_label.pkl

# model
model: model.aagcn_v33.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_subset: 3
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: "spatial"
  in_channels: 3
  drop_out: 0
  adaptive: True
  attention: True
  kernel_size: 3
  pad: False
  backbone_dim: 16
  t_trans_cfg:
    num_heads: 25
    model_dim: 16
    ffn_dim: 64
    dropout: 0.2
    activation: gelu
    prenorm: False
    num_layers: 3
    length: 201
    pos_emb: rel-shared
  s_trans_cfg:
    num_heads: 1
    model_dim: 16
    ffn_dim: 64
    dropout: 0.2
    activation: gelu
    prenorm: False
    num_layers: 3
    length: 25
    pos_emb: rel-shared
  add_A: True
  add_Aa: True
  trans_seq: sa-t-v2
  multi_trans_dropout: 0.2
  res_dropout: 0.2
  pos_enc: None
  classifier_type: CLS
  model_layers: 101
#  gbn_split: 2
# weights: None

#optim
# device: [0, 1 ,2, 3]
device: [0]
batch_size: 2
test_batch_size: 2

optimizer: SGD-LLRD
nesterov: True
base_lr: 0.01
step: [30, 40]
weight_decay: 0.0001
llrd_factor: 0.5

start_epoch: 0
num_epoch: 50
warm_up_epoch: 0

only_train_part: False
only_train_epoch: 5
