work_dir: ./data/data/ntu_result/xview/aagcn_v37_joint/220319103001_cossin_ddp_9l1cSE6_0bb_01lr_subsample20
model_saved_name: ./data/data/ntu_result/xview/aagcn_v37_joint/220319103001_cossin_ddp_9l1cSE6_0bb_01lr_subsample20/ntu_cv_aagcn_joint

phase: train
save_score: True

seed: 1
log_interval: 100 # iter
save_interval: 2 # iter
eval_interval: 5 # iter
print_log: true

# feeder
feeder: feeders.feeder.Feeder
num_worker: 1
train_feeder_args:
  #  data_path: ./data/data/ntu_stretched/xview/train_data_joint.npy
  #  label_path: ./data/data/ntu_stretched/xview/train_label.pkl
  data_path: ./data/data/ntu_nopad/xview/train_data_joint.npy
  label_path: ./data/data/ntu_nopad/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
  random_zaxis_flip: False
  random_xaxis_scale: False
  random_yaxis_scale: False
  random_subsample: 20

test_feeder_args:
  #  data_path: ./data/data/ntu_stretched/xview/val_data_joint.npy
  #  label_path: ./data/data/ntu_stretched/xview/val_label.pkl
  data_path: ./data/data/ntu_nopad/xview/val_data_joint.npy
  label_path: ./data/data/ntu_nopad/xview/val_label.pkl

# model
model: model.aagcn_v37.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_subset: 3
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: "spatial"
  in_channels: 3
  drop_out: 0
  adaptive: True
  attention: True
  kernel_size: 3
  stride: 1
  pad: True
  backbone_dim: 16
  model_layers: 0
  t_trans_cfg:
    dim: 150 # mvc
    depth: 1
    heads: 6
    dim_head: 25
    mlp_dim: 600
    dropout: 0.2
    num_layers: 9
    length: 101
    pos_emb: rel-shared
  s_trans_cfg:
    dim: 120 # mtc
    depth: 1
    heads: 6
    dim_head: 20
    mlp_dim: 360
    dropout: 0.2
    num_layers: 9
    length: 26
    pos_emb: rel-shared
  c_trans_cfg:
    depth: 1
    sm_dim: 150
    sm_heads: 6
    sm_dim_head: 25
    sm_dropout: 0.2
    lg_dim: 120
    lg_heads: 6
    lg_dim_head: 20
    lg_dropout: 0.2
    num_layers: 1
  trans_mode: None
  pos_enc: cossin
  add_s_cls_token: True
  add_t_cls_token: True
  classifier_type: CLS-POOL

# optim
device: [0, 1]
batch_size: 32
test_batch_size: 32

optimizer: SGD
nesterov: True
base_lr: 0.1
step: [30, 40]
weight_decay: 0.0001
# llrd_factor: 1.0
# scheduler: onecyclelr
# anneal_strategy: cos
# eps: 0.0001

start_epoch: 0
num_epoch: 50
warm_up_epoch: 5

only_train_part: False
only_train_epoch: 5

world_size : 2
ddp : True
