work_dir: ./data/data/ntu_result/xview/sgn_v2_j15/220404110001
model_saved_name: ./data/data/ntu_result/xview/sgn_v2_j15/220404110001/sgn

phase: train
save_score: True

seed: 1337
log_interval: 100 # iter
save_interval: 2 # epoch
eval_interval: 1 # epoch
print_log: true

# feeder
feeder: feeders.feeder.Feeder
num_worker: 16
train_feeder_args:
  data_path: ./data/data/ntu_sgn/processed_data/NTU_CV_train.pkl
  label_path: ./data/data/ntu_sgn/processed_data/NTU_CV_train_label.pkl
  dataset: NTU60-CV-SGN
  debug: False
  joint_15: True

train_dataloader_args:
  dataset: NTU60-CV-SGN
  seg: 20
  multi_test: 1

test_feeder_args:
  data_path: ./data/data/ntu_sgn/processed_data/NTU_CV_test.pkl
  label_path: ./data/data/ntu_sgn/processed_data/NTU_CV_test_label.pkl
  dataset: NTU60-CV-SGN
  debug: True
  joint_15: True

test_dataloader_args:
  dataset: NTU60-CV-SGN
  seg: 20
  multi_test: 5

use_sgn_dataloader: True

# model
model: model.sgn_v2.SGN
model_args:
  num_class: 60
  num_point: 15
  in_channels: 3
  seg: 20
  bias: True
  # g_proj_shared: True
  # part: 1
  # motion: 2
  # aspp: [0, 1, 3, 5]
  # t_kernel: 3
  # t_max_pool: False
  # subject: True
  c_multiplier: 1
  dropout: 0.0

label_smoothing: 0.1

# weights: ./data/data/ntu_result/xview/sgn_v2/220327213001_1337/sgn-119-70560.pt

# optim
device: [0]
batch_size: 64
test_batch_size: 4

optimizer: Adam
nesterov: True
base_lr: 0.001
step: [60, 90, 110]
weight_decay: 0.0001
# llrd_factor: 1.0
# scheduler: onecyclelr
# anneal_strategy: cos
# eps: 0.0001

start_epoch: 0
num_epoch: 120
warm_up_epoch: 0

only_train_part: False
only_train_epoch: 5

world_size: 1
ddp: False
