work_dir: ./data/ntu_result/run1/xview/agcn_joint
model_saved_name: ./data/ntu_result/run1/xview/agcn_joint/ntu_cv_agcn_joint

phase: train
save_score: True

seed: 1
log_interval: 100  # iter
save_interval: 2  # iter
eval_interval: 5  # iter
print_log: true

# feeder
feeder: feeders.feeder.Feeder
num_worker: 4
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint.npy
  label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl

# model
model: model.aagcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
# device: [0, 1 ,2, 3]
device: [0]
batch_size: 8  #64
test_batch_size: 1  #64

optimizer: SGD
nesterov: True
base_lr: 0.1
step: [30, 40]
weight_decay: 0.0001

start_epoch: 0
num_epoch: 50
warm_up_epoch: 0
